name: Build, Test, and Run JAR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Загрузка кода в Git Actions
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Настройка JDK
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Шаг 3: Запуск тестов и создание jar
    - name: Build with Maven
      run: mvn clean package

    # Шаг 4: Запуск тестов
    - name: Run tests
      run: mvn test

    # Шаг 5: Запустить
    - name: Run JAR
      run: java -jar runme.jar
